
# Learning Docker
# by @thepeg
# https://github.com/marcopeg/learning-docker

# setup a Wordpress development environment

version: '2'
services:

#################
# Data Services #
#################

    # collect
    storage:
        image: busybox:latest
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./wp-content/uploads:/var/www/html/wp-content/uploads
            - ./wp-content/plugins:/var/www/html/wp-content/plugins
            - ./wp-content/themes:/var/www/html/wp-content/themes
            - ./libs/node:/usr/src/app/lib

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes_from:
            - storage

    redis:
        image: redis:latest

    rabbitmq:
        image: rabbitmq:latest







################
# APPLICATIONS #
################

    # custom wordpress image - good for development
    wordpress:
        build: ./services/wordpress
        links:
            - mysql:mysql
            - cache_trigger:cache_trigger
        environment:
            WORDPRESS_DB_PASSWORD: root
        volumes_from:
            - storage
        depends_on:
            - mysql

    # node app which exposes an interface to start the caching process
    cache_trigger:
        build: ./services/node
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - rabbitmq
        environment:
            NODE_ENV: development
        volumes_from:
            - storage
        volumes:
            - ./apps/cache_trigger:/usr/src/app
            - ./data/node_modules/cache_trigger:/usr/src/app/node_modules

    # node app which fetches the posts index and sets up the single posts
    # caching mechanism
    cache_posts_list:
        build: ./services/node
        links:
            - wordpress:wordpress
            - redis:redis
            - rabbitmq:rabbitmq
        depends_on:
            - wordpress
            - redis
            - rabbitmq
        environment:
            NODE_ENV: development
        volumes_from:
            - storage
        volumes:
            - ./apps/cache_posts_list:/usr/src/app
            - ./data/node_modules/cache_posts_list:/usr/src/app/node_modules

    # node app which listen to rabbitmq, pull from wordpress
    # and push to redis
    cache_single_post:
        build: ./services/node
        links:
            - wordpress:wordpress
            - redis:redis
            - rabbitmq:rabbitmq
        depends_on:
            - wordpress
            - redis
            - rabbitmq
        environment:
            NODE_ENV: development
        volumes_from:
            - storage
        volumes:
            - ./apps/cache_single_post:/usr/src/app
            - ./data/node_modules/cache_single_post:/usr/src/app/node_modules

    # node app which listen to rabbitmq, pull from wordpress
    # and push to redis
    api:
        build: ./services/node
        links:
            - redis:redis
        depends_on:
            - redis
        environment:
            NODE_ENV: development
        volumes_from:
            - storage
        volumes:
            - ./apps/api:/usr/src/app
            - ./data/node_modules/api:/usr/src/app/node_modules

    client:
        build: ./services/frontend
        links:
            - api:api
        environment:
            NODE_ENV: development
        ports:
            - 8080:8080
        volumes_from:
            - storage
        volumes:
            - ./apps/client:/usr/src/app
            - ./data/node_modules/client:/usr/src/app/node_modules
        stdin_open: true
        tty: true



#########################
# Development Utilities #
#########################

    # database utility
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PHP_UPLOAD_MAX_FILESIZE: 999999999
        depends_on:
            - mysql

    # redis web based gui
    redis_commander:
        build: ./services/redis-ui
        links:
            - redis:redis





##################
# Frontent NGiNX #
##################

    # reverse proxy to the services we want to expose to the host
    # by default all the services are hidden behind Docker's layer
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 8081:8081
        links:
            - phpmyadmin:phpmyadmin_service
            - wordpress:wordpress_service
            - redis_commander:redis_commander_service
            - cache_trigger:cache_trigger_service
            - api:api_service
            # - client:client_service
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
