
# Learning Docker
# by @thepeg
# https://github.com/marcopeg/learning-docker

# setup a Wordpress development environment

version: '2'
services:

    storage:
        image: busybox:latest
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/wp-content:/var/www/html/wp-content
            - ./wp-content/uploads:/var/www/html/wp-content/uploads
            - ./wp-content/plugins:/var/www/html/wp-content/plugins
            - ./wp-content/themes:/var/www/html/wp-content/themes

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes_from:
            - storage
        ports:
            - 3306:3306

    redis:
        image: redis:latest
        ports:
            - 6379:6379

    wordpress:
        build: ./services/wordpress
        links:
            - mysql:mysql
        environment:
            WORDPRESS_DB_PASSWORD: root
        ports:
            - 8081:80
        volumes_from:
            - storage
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8082:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PHP_UPLOAD_MAX_FILESIZE: 999999999
        depends_on:
            - mysql

    cache:
        build: ./services/node
        ports:
            - 8083:8080
        volumes:
            - ./cache:/usr/src/app
        links:
            - mysql:mysql
            - redis:redis
            - wordpress:wordpress
        environment:
            NODE_ENV: development
        command: ["supervisor", "app.js"]
        depends_on:
            - redis
